// PAGE BUILDER — pure model helpers for the Outline tab and the Code tab.
//
// Dependency-free ON PURPOSE (no JSX, no lucide, no blockRegistry import) so
// node can exercise them directly — see server/tests/builder/builder-model.mjs.
// Anything registry-shaped (labels, icons) is INJECTED by the caller rather
// than imported, which is also what keeps these functions total: they are fed
// whatever the server had in `blocks`, including rows that predate any schema.
//
// TOTALITY IS THE POINT. `blocks` is operator/AI-authored JSON that has only
// ever been validated for `type: string` + `props: object` (funnels.js
// validateBlocks) — it can legally contain a `row` whose `columns` is a
// string, a block with no id, or a null in the array. None of that may throw
// inside a render pass, so every function here drops what it cannot read.

// ---------------------------------------------------------------------------
// Outline
// ---------------------------------------------------------------------------

/** Fallback label when the caller injects no labelFor. */
export function defaultLabel(block) {
  const name = block && block.props && typeof block.props === 'object' ? block.props.block_name : null;
  if (typeof name === 'string' && name.trim()) return name.trim();
  const type = block && typeof block.type === 'string' ? block.type : '';
  return type || 'Unknown';
}

/**
 * Flatten `blocks` into outline rows.
 *
 * Every TOP-LEVEL row carries `index` — the position in the blocks array,
 * which is what reorder/move operate on. Child rows (a `row` block's columns)
 * are presentation only: they are NOT independently movable, so they carry
 * `movable:false` and their `index` points at the PARENT. A drag handler that
 * reads `index` off a child therefore reorders the parent rather than
 * corrupting the array with a column index.
 *
 * @param {unknown} blocks   the raw blocks array
 * @param {(b:object)=>string} [labelFor]  registry-aware label resolver
 * @returns {Array<{key:string,id:string|null,index:number,type:string,label:string,depth:number,movable:boolean,parentId:string|null}>}
 */
export function buildOutline(blocks, labelFor) {
  const label = typeof labelFor === 'function' ? labelFor : defaultLabel;
  const rows = [];
  const list = Array.isArray(blocks) ? blocks : [];
  for (let index = 0; index < list.length; index += 1) {
    const b = list[index];
    // A null/primitive entry cannot be selected or labelled — skipping it
    // keeps the outline honest rather than rendering a ghost row.
    if (!b || typeof b !== 'object' || Array.isArray(b)) continue;
    const type = typeof b.type === 'string' && b.type ? b.type : 'unknown';
    const id = typeof b.id === 'string' && b.id ? b.id : null;
    rows.push({
      key: id || `idx_${index}`,
      id,
      index,
      type,
      label: String(label(b) ?? '') || type,
      depth: 0,
      movable: true,
      parentId: null,
    });
    // `row` blocks nest columns. Anything else with a columns prop is not a
    // row and must not sprout children.
    if (type !== 'row') continue;
    const props = b.props && typeof b.props === 'object' ? b.props : {};
    const cols = Array.isArray(props.columns) ? props.columns : [];
    for (let c = 0; c < cols.length; c += 1) {
      rows.push({
        key: `${id || `idx_${index}`}__col${c}`,
        id,
        index,
        type: 'column',
        label: `Column ${c + 1}`,
        depth: 1,
        movable: false,
        parentId: id,
      });
    }
  }
  return rows;
}

// ---------------------------------------------------------------------------
// Code tab
// ---------------------------------------------------------------------------

// WHICH BLOCKS ARE EDITABLE AS TEXT, AND WHY THE REST ARE NOT.
//
// The public page's HTML is generated by the SERVER (funnelRender.js
// renderBlockInner). The builder does not own that function and must not
// re-implement it — a client-side copy would drift and start showing operators
// markup the live page never emits.
//
// So the Code tab is honest about a boundary: blocks whose markup IS a prop
// (the escape-hatch family) round-trip as text through the same blocks PATCH
// every other edit uses; every other block shows its props read-only with a
// note saying the server generates its markup. Documented in the delivery
// report as the deferred half of "full per-block code".
export const CODE_EDITABLE_PROPS = {
  custom_html: { html: 'html', css: 'css' },
  html: { html: 'html', css: null },
  embed: { html: 'html', css: null },
  section: { html: 'html', css: null },
  text: { html: 'html', css: null }, // the advanced verbatim override
};

export const SERVER_GENERATED_NOTE =
  'Markup for this block is generated by the server renderer from the props below. Edit it on the Builder tab — or convert the block to Custom HTML to own the markup as text.';

/**
 * Build the Code tab's per-block sections.
 *
 * `html` / `css` are the CURRENT prop values (empty string when unset, never
 * null — a controlled textarea fed null flips to uncontrolled and React warns
 * once then silently stops tracking edits).
 *
 * @param {unknown} blocks
 * @param {(b:object)=>string} [labelFor]
 * @returns {Array<{key:string,id:string|null,index:number,type:string,label:string,editable:boolean,htmlProp:string|null,cssProp:string|null,html:string,css:string,note:string,propsJson:string}>}
 */
export function blockCodeSections(blocks, labelFor) {
  const label = typeof labelFor === 'function' ? labelFor : defaultLabel;
  const out = [];
  const list = Array.isArray(blocks) ? blocks : [];
  for (let index = 0; index < list.length; index += 1) {
    const b = list[index];
    if (!b || typeof b !== 'object' || Array.isArray(b)) continue;
    const type = typeof b.type === 'string' && b.type ? b.type : 'unknown';
    const id = typeof b.id === 'string' && b.id ? b.id : null;
    const props = b.props && typeof b.props === 'object' && !Array.isArray(b.props) ? b.props : {};
    const map = CODE_EDITABLE_PROPS[type] || null;
    // An editable section needs a WRITE TARGET. Without an id the PATCH has
    // nothing to address, so the section degrades to read-only rather than
    // offering a textarea whose edits would land nowhere.
    const editable = !!map && !!id;
    out.push({
      key: id || `idx_${index}`,
      id,
      index,
      type,
      label: String(label(b) ?? '') || type,
      editable,
      htmlProp: editable ? map.html : null,
      cssProp: editable ? map.css : null,
      html: editable && map.html && typeof props[map.html] === 'string' ? props[map.html] : '',
      css: editable && map.css && typeof props[map.css] === 'string' ? props[map.css] : '',
      note: editable ? '' : map ? 'This block has no id yet — reopen the page to edit it as text.' : SERVER_GENERATED_NOTE,
      propsJson: safeJson(props),
    });
  }
  return out;
}

/**
 * JSON.stringify that cannot throw. `blocks` has survived a server round-trip
 * so a cycle is not reachable through the API — but the in-memory array is
 * also written by the AI-ops path, and a Code tab that white-screens is a
 * worse outcome than one that says it cannot display a block.
 */
export function safeJson(value) {
  try {
    const s = JSON.stringify(value, null, 2);
    return typeof s === 'string' ? s : String(s);
  } catch {
    return '/* not displayable — this block contains a circular reference */';
  }
}

/**
 * Count the sections a Code tab can actually edit — drives the boundary note
 * ("N of M blocks are editable as text here") so the limitation is stated as
 * a number rather than discovered block by block.
 */
export function editableCount(sections) {
  return (Array.isArray(sections) ? sections : []).filter((s) => s && s.editable).length;
}

// ---------------------------------------------------------------------------
// Order bump
// ---------------------------------------------------------------------------

const AMP_RE = /&/g;
const LT_RE = /</g;
const GT_RE = />/g;

/** Escape every HTML-special character. The base case for the sanitizer. */
export function escapeHtml(s) {
  return String(s == null ? '' : s)
    .replace(AMP_RE, '&amp;')
    .replace(LT_RE, '&lt;')
    .replace(GT_RE, '&gt;');
}

/**
 * ALLOW-LIST parser for the bump description: `<b>` and `<u>` are honoured,
 * EVERYTHING else stays literal text.
 *
 * Returns SEGMENTS, not an HTML string, on purpose. BlockPreview.jsx holds a
 * hard invariant — no dangerouslySetInnerHTML anywhere in the admin DOM, all
 * operator text through React text nodes — and returning markup would force
 * that invariant to be broken here. Segments let the caller render
 * <strong>/<u> elements around auto-escaped text instead, so hostile input
 * cannot become markup at all rather than merely being filtered.
 *
 * Unknown tags, attributes on the allowed tags (`<b onclick=…>`), and unclosed
 * tags are all simply not recognised by the regex, so they fall through as
 * literal characters — the failure mode is "shows the angle brackets", never
 * "executes".
 *
 * CANVAS-ONLY. The server renderer esc()'s the whole description, so this
 * markup shows as literal text on the published page until the integrator
 * lands the matching renderer change (noted in the delivery report).
 *
 * @returns {Array<{text:string,bold:boolean,underline:boolean}>}
 */
export function parseInlineMarkup(text) {
  const src = String(text == null ? '' : text);
  const out = [];
  let bold = 0;
  let underline = 0;
  let buf = '';
  const flush = () => {
    if (!buf) return;
    out.push({ text: buf, bold: bold > 0, underline: underline > 0 });
    buf = '';
  };
  const re = /<(\/?)([bu])>/gi;
  let last = 0;
  let m;
  while ((m = re.exec(src))) {
    buf += src.slice(last, m.index);
    flush();
    const closing = m[1] === '/';
    const tag = m[2].toLowerCase();
    if (tag === 'b') bold = closing ? Math.max(0, bold - 1) : bold + 1;
    else underline = closing ? Math.max(0, underline - 1) : underline + 1;
    last = m.index + m[0].length;
  }
  buf += src.slice(last);
  flush();
  return out;
}

/**
 * The checkbox headline shown on the canvas.
 *
 * Blank `headline` AUTO-BUILDS from the offer name and the display price —
 * which is the picked variant's live Shopify price, written into props.price
 * by the picker. With no price we say less rather than inventing a number: a
 * headline reading "for ONLY $" would be a claim about money we do not have.
 */
export function bumpHeadline(props) {
  // NOT a destructuring default: `= {}` only fires for `undefined`, and the
  // caller passes `block.props`, which is legally null on a block the API
  // accepted. Destructuring null throws.
  const p = props && typeof props === 'object' ? props : {};
  const { headline, offer_name: offerName, price } = p;
  const explicit = typeof headline === 'string' ? headline.trim() : '';
  if (explicit) return explicit;
  const name = typeof offerName === 'string' ? offerName.trim() : '';
  const amount = typeof price === 'string' ? price.trim() : price != null ? String(price).trim() : '';
  if (name && amount) return `Yes, I want the ${name} for ONLY ${amount}`;
  if (name) return `Yes, I want the ${name}`;
  return 'Yes, I want the offer';
}

/**
 * True when the bump has no product wired — the state the canvas must call
 * out, and the state the server refuses with 422 bump_not_chargeable.
 */
export function bumpUnconfigured(props) {
  const p = props && typeof props === 'object' ? props : {};
  return !String(p.variant_id ?? '').trim();
}

/**
 * The server refuses a duplicate page slug with 409 "A page with this slug
 * already exists in this funnel" (routes/funnels.js). Detecting it lets the
 * panel put the refusal NEXT TO THE FIELD THAT CAUSED IT instead of leaving
 * the operator to connect a top-bar banner to a box three sections away.
 *
 * Matched on the message rather than the status because the save engine
 * surfaces `err.response.data.error` — a string — and never the code.
 */
export function isSlugCollision(saveError) {
  return /slug already exists/i.test(String(saveError == null ? '' : saveError));
}

/**
 * `data-blk-name` hook value. Empty (→ attribute omitted) unless the operator
 * named the block, so an unnamed block emits no attribute at all.
 */
export function blockNameAttr(props) {
  const p = props && typeof props === 'object' ? props : {};
  const name = typeof p.block_name === 'string' ? p.block_name.trim() : '';
  return name;
}
