// PAGE BUILDER — pure model helpers for the Outline tab and the Code tab.
//
// Dependency-free ON PURPOSE (no JSX, no lucide, no blockRegistry import) so
// node can exercise them directly — see server/tests/builder/builder-model.mjs.
// Anything registry-shaped (labels, icons) is INJECTED by the caller rather
// than imported, which is also what keeps these functions total: they are fed
// whatever the server had in `blocks`, including rows that predate any schema.
//
// TOTALITY IS THE POINT. `blocks` is operator/AI-authored JSON that has only
// ever been validated for `type: string` + `props: object` (funnels.js
// validateBlocks) — it can legally contain a `row` whose `columns` is a
// string, a block with no id, or a null in the array. None of that may throw
// inside a render pass, so every function here drops what it cannot read.

// ---------------------------------------------------------------------------
// Outline
// ---------------------------------------------------------------------------

/** Fallback label when the caller injects no labelFor. */
export function defaultLabel(block) {
  const name = block && block.props && typeof block.props === 'object' ? block.props.block_name : null;
  if (typeof name === 'string' && name.trim()) return name.trim();
  const type = block && typeof block.type === 'string' ? block.type : '';
  return type || 'Unknown';
}

/**
 * Flatten `blocks` into outline rows.
 *
 * Every TOP-LEVEL row carries `index` — the position in the blocks array,
 * which is what reorder/move operate on. Child rows (a `row` block's columns)
 * are presentation only: they are NOT independently movable, so they carry
 * `movable:false` and their `index` points at the PARENT. A drag handler that
 * reads `index` off a child therefore reorders the parent rather than
 * corrupting the array with a column index.
 *
 * @param {unknown} blocks   the raw blocks array
 * @param {(b:object)=>string} [labelFor]  registry-aware label resolver
 * @returns {Array<{key:string,id:string|null,index:number,type:string,label:string,depth:number,movable:boolean,parentId:string|null}>}
 */
export function buildOutline(blocks, labelFor) {
  const label = typeof labelFor === 'function' ? labelFor : defaultLabel;
  const rows = [];
  const list = Array.isArray(blocks) ? blocks : [];
  // F17. Ids are supposed to be unique, but `blocks` is operator/AI-authored
  // and a duplicated id is reachable (a hand-edited paste, an AI insert_block
  // echoing an existing id). Two React children with the same key silently
  // drop one row, so the key is disambiguated by position — the DISPLAY stays
  // honest even when the data is not.
  const keyCount = new Map();
  const uniqueKey = (base) => {
    const n = keyCount.get(base) || 0;
    keyCount.set(base, n + 1);
    return n === 0 ? base : `${base}__dup${n}`;
  };
  for (let index = 0; index < list.length; index += 1) {
    const b = list[index];
    // A null/primitive entry cannot be selected or labelled — skipping it
    // keeps the outline honest rather than rendering a ghost row.
    if (!b || typeof b !== 'object' || Array.isArray(b)) continue;
    const type = typeof b.type === 'string' && b.type ? b.type : 'unknown';
    const id = typeof b.id === 'string' && b.id ? b.id : null;
    rows.push({
      key: uniqueKey(id || `idx_${index}`),
      id,
      index,
      type,
      label: String(label(b) ?? '') || type,
      depth: 0,
      movable: true,
      parentId: null,
    });
    // `row` blocks nest columns. Anything else with a columns prop is not a
    // row and must not sprout children.
    if (type !== 'row') continue;
    const props = b.props && typeof b.props === 'object' ? b.props : {};
    const cols = Array.isArray(props.columns) ? props.columns : [];
    for (let c = 0; c < cols.length; c += 1) {
      rows.push({
        key: uniqueKey(`${id || `idx_${index}`}__col${c}`),
        id,
        index,
        type: 'column',
        label: `Column ${c + 1}`,
        depth: 1,
        movable: false,
        parentId: id,
      });
    }
  }
  return rows;
}

// ---------------------------------------------------------------------------
// Code tab
// ---------------------------------------------------------------------------

// WHICH BLOCKS ARE EDITABLE AS TEXT, AND WHY THE REST ARE NOT.
//
// The public page's HTML is generated by the SERVER (funnelRender.js
// renderBlockInner). The builder does not own that function and must not
// re-implement it — a client-side copy would drift and start showing operators
// markup the live page never emits.
//
// So the Code tab is honest about a boundary: blocks whose markup IS a prop
// (the escape-hatch family) round-trip as text through the same blocks PATCH
// every other edit uses; every other block shows its props read-only with a
// note saying the server generates its markup. Documented in the delivery
// report as the deferred half of "full per-block code".
export const CODE_EDITABLE_PROPS = {
  custom_html: { html: 'html', css: 'css' },
  html: { html: 'html', css: null },
  embed: { html: 'html', css: null },
  section: { html: 'html', css: null },
  text: { html: 'html', css: null }, // the advanced verbatim override
};

export const SERVER_GENERATED_NOTE =
  'Markup for this block is generated by the server renderer from the props below. Edit it on the Builder tab — or convert the block to Custom HTML to own the markup as text.';

/**
 * Build the Code tab's per-block sections.
 *
 * `html` / `css` are the CURRENT prop values (empty string when unset, never
 * null — a controlled textarea fed null flips to uncontrolled and React warns
 * once then silently stops tracking edits).
 *
 * @param {unknown} blocks
 * @param {(b:object)=>string} [labelFor]
 * @returns {Array<{key:string,id:string|null,index:number,type:string,label:string,editable:boolean,htmlProp:string|null,cssProp:string|null,html:string,css:string,note:string,propsJson:string}>}
 */
export function blockCodeSections(blocks, labelFor) {
  const label = typeof labelFor === 'function' ? labelFor : defaultLabel;
  const out = [];
  const list = Array.isArray(blocks) ? blocks : [];
  for (let index = 0; index < list.length; index += 1) {
    const b = list[index];
    if (!b || typeof b !== 'object' || Array.isArray(b)) continue;
    const type = typeof b.type === 'string' && b.type ? b.type : 'unknown';
    const id = typeof b.id === 'string' && b.id ? b.id : null;
    const props = b.props && typeof b.props === 'object' && !Array.isArray(b.props) ? b.props : {};
    const map = CODE_EDITABLE_PROPS[type] || null;
    // An editable section needs a WRITE TARGET. Without an id the PATCH has
    // nothing to address, so the section degrades to read-only rather than
    // offering a textarea whose edits would land nowhere.
    const editable = !!map && !!id;
    out.push({
      key: id || `idx_${index}`,
      id,
      index,
      type,
      label: String(label(b) ?? '') || type,
      editable,
      htmlProp: editable ? map.html : null,
      cssProp: editable ? map.css : null,
      html: editable && map.html && typeof props[map.html] === 'string' ? props[map.html] : '',
      css: editable && map.css && typeof props[map.css] === 'string' ? props[map.css] : '',
      note: editable ? '' : map ? 'This block has no id yet — reopen the page to edit it as text.' : SERVER_GENERATED_NOTE,
      propsJson: safeJson(props),
    });
  }
  return out;
}

/**
 * JSON.stringify that cannot throw. `blocks` has survived a server round-trip
 * so a cycle is not reachable through the API — but the in-memory array is
 * also written by the AI-ops path, and a Code tab that white-screens is a
 * worse outcome than one that says it cannot display a block.
 */
export function safeJson(value) {
  try {
    const s = JSON.stringify(value, null, 2);
    return typeof s === 'string' ? s : String(s);
  } catch {
    return '/* not displayable — this block contains a circular reference */';
  }
}

/**
 * Count the sections a Code tab can actually edit — drives the boundary note
 * ("N of M blocks are editable as text here") so the limitation is stated as
 * a number rather than discovered block by block.
 */
export function editableCount(sections) {
  return (Array.isArray(sections) ? sections : []).filter((s) => s && s.editable).length;
}

// ---------------------------------------------------------------------------
// Order bump
// ---------------------------------------------------------------------------

const AMP_RE = /&/g;
const LT_RE = /</g;
const GT_RE = />/g;

/** Escape every HTML-special character. The base case for the sanitizer. */
export function escapeHtml(s) {
  return String(s == null ? '' : s)
    .replace(AMP_RE, '&amp;')
    .replace(LT_RE, '&lt;')
    .replace(GT_RE, '&gt;');
}

/**
 * ALLOW-LIST parser for the bump description: `<b>` and `<u>` are honoured,
 * EVERYTHING else stays literal text.
 *
 * Returns SEGMENTS, not an HTML string, on purpose. BlockPreview.jsx holds a
 * hard rule — no dangerouslySetInnerHTML in that file, all operator text
 * through React text nodes — and returning markup would force that rule to be
 * broken there. Segments let the caller render <strong>/<u> elements around
 * auto-escaped text instead, so hostile input cannot become markup at all
 * rather than merely being filtered.
 *
 * (CodeTab.jsx is the ONE audited exception in the builder: its highlight
 * overlay sets innerHTML from codeFormat.js's highlighters, which escape every
 * source character with escHtml() before wrapping it in <span> tags — the
 * output is escaped text plus a fixed set of class-only spans, and the layer
 * is aria-hidden and pointer-events:none.)
 *
 * Unknown tags, attributes on the allowed tags (`<b onclick=…>`), and unclosed
 * tags are all simply not recognised by the regex, so they fall through as
 * literal characters — the failure mode is "shows the angle brackets", never
 * "executes".
 *
 * MATCHED BY THE RENDERER. funnelRender.js escapes the whole description and
 * then un-escapes exactly `<b>`/`</b>`/`<u>`/`</u>`, so the published page
 * shows the same two tags this canvas parser shows — and nothing else.
 *
 * @returns {Array<{text:string,bold:boolean,underline:boolean}>}
 */
export function parseInlineMarkup(text) {
  const src = String(text == null ? '' : text);
  const out = [];
  let bold = 0;
  let underline = 0;
  let buf = '';
  const flush = () => {
    if (!buf) return;
    out.push({ text: buf, bold: bold > 0, underline: underline > 0 });
    buf = '';
  };
  const re = /<(\/?)([bu])>/gi;
  let last = 0;
  let m;
  while ((m = re.exec(src))) {
    buf += src.slice(last, m.index);
    flush();
    const closing = m[1] === '/';
    const tag = m[2].toLowerCase();
    if (tag === 'b') bold = closing ? Math.max(0, bold - 1) : bold + 1;
    else underline = closing ? Math.max(0, underline - 1) : underline + 1;
    last = m.index + m[0].length;
  }
  buf += src.slice(last);
  flush();
  return out;
}

/**
 * The checkbox headline shown on the canvas.
 *
 * Blank `headline` AUTO-BUILDS from the offer name and the display price —
 * which is the picked variant's live Shopify price, written into props.price
 * by the picker. With no price we say less rather than inventing a number: a
 * headline reading "for ONLY $" would be a claim about money we do not have.
 */
export const BUMP_DEFAULT_HEADLINE = 'Yes! Add this one-time offer to my order';
export const BUMP_DEFAULT_NAME_COLOR = '#111827';

/**
 * MIRRORS THE SERVER EXACTLY. funnelRender.js order_bump:
 *
 *   p.headline  ->  offer_name ? `Yes, I want the ${offer_name}!`
 *               ->  p.label    ->  the default string
 *
 * NOTE WHAT IS ABSENT: the server's auto-headline carries NO PRICE. An earlier
 * draft of this function built "…for ONLY $19" from props.price, which would
 * have made the canvas advertise a number the published page never prints —
 * a preview that lies about money. The precedence and the wording here are
 * copied from the renderer, not invented, and the harness pins them.
 */
export function bumpHeadline(props) {
  // NOT a destructuring default: `= {}` only fires for `undefined`, and the
  // caller passes `block.props`, which is legally null on a block the API
  // accepted. Destructuring null throws.
  const p = props && typeof props === 'object' ? props : {};
  const headline = typeof p.headline === 'string' ? p.headline.trim() : '';
  if (headline) return headline;
  const name = typeof p.offer_name === 'string' ? p.offer_name.trim() : '';
  if (name) return `Yes, I want the ${name}!`;
  const label = typeof p.label === 'string' ? p.label.trim() : '';
  if (label) return label;
  return BUMP_DEFAULT_HEADLINE;
}

/**
 * The offer-name colour the server will actually use: a STRICT hex, or its
 * default ink. The renderer tests `^#[0-9a-fA-F]{3,8}$` and silently falls
 * back — so the canvas must fall back on exactly the same inputs, or an
 * operator typing `red` sees red here and near-black on the live page.
 */
export function bumpNameColor(props) {
  const p = props && typeof props === 'object' ? props : {};
  const raw = String(p.offer_name_color == null ? '' : p.offer_name_color);
  return /^#[0-9a-fA-F]{3,8}$/.test(raw) ? raw : BUMP_DEFAULT_NAME_COLOR;
}

/**
 * F15. A price is only a price when it names an AMOUNT. `0`, `'0'`, `'$0.00'`,
 * `''` and null all mean "no price to advertise". Used for the canvas's
 * secondary "from …" line, which is builder chrome — the server prints
 * props.price verbatim when it is non-blank.
 */
export function displayPrice(price) {
  if (price == null) return '';
  const s = String(price).trim();
  if (!s) return '';
  // Strip currency symbols/separators to ask "is this numerically zero?"
  const numeric = s.replace(/[^0-9.-]/g, '');
  if (numeric && Number(numeric) === 0) return '';
  return s;
}

/**
 * True when the bump has no product wired — the state the canvas must call
 * out, and the state the server refuses with 422 bump_not_chargeable.
 */
export function bumpUnconfigured(props) {
  const p = props && typeof props === 'object' ? props : {};
  // F14. `||` not `??`, matching the server EXACTLY: checkoutPublic does
  // `String(bp.variant_id || '').trim()`, so variant_id = 0 / '' / false is
  // unwired THERE. `??` would call 0 configured here and the canvas would
  // promise a charge the server refuses with 422 bump_not_chargeable.
  return !String(p.variant_id || '').trim();
}

/**
 * The server refuses a duplicate page slug with 409 "A page with this slug
 * already exists in this funnel" (routes/funnels.js). Detecting it lets the
 * panel put the refusal NEXT TO THE FIELD THAT CAUSED IT instead of leaving
 * the operator to connect a top-bar banner to a box three sections away.
 *
 * Matched on the message rather than the status because the save engine
 * surfaces `err.response.data.error` — a string — and never the code.
 */
export function isSlugCollision(saveError) {
  // F16. Scoped to the PAGE refusal. The funnel-level message
  // ("A funnel with this slug already exists") is a different field on a
  // different screen — matching it would point the operator at the page slug
  // box for a problem that is not there.
  return /A page with this slug already exists/i.test(String(saveError == null ? '' : saveError));
}

/**
 * `data-blk-name` hook value. Empty (→ attribute omitted) unless the operator
 * named the block, so an unnamed block emits no attribute at all.
 */
export function blockNameAttr(props) {
  const p = props && typeof props === 'object' ? props : {};
  const name = typeof p.block_name === 'string' ? p.block_name.trim() : '';
  return name;
}

/**
 * Which DIRTY FIELD a save refusal names, or null when the refusal is not
 * about one field in particular.
 *
 * The save engine sends every dirty field in ONE PATCH. When the server
 * refuses, re-dirtying the whole set means the offending field rides along on
 * every later save too — one slug collision then refuses the operator's next
 * hour of block edits. Naming the field lets the engine hold back that one and
 * let the rest through.
 *
 * Message-matched, not status-matched, for the same reason isSlugCollision is:
 * the engine only ever sees `err.response.data.error`, a string.
 */
export function refusedSaveField(saveError) {
  if (isSlugCollision(saveError)) return 'slug';
  return null;
}

/**
 * The fields a refused PATCH should leave DIRTY, so the next flush resends
 * them. Everything the request carried, minus the one field the refusal names.
 *
 * Dropping only the named field is the point: a rejected save must never
 * silently lose an edit, but re-queueing the field the server just refused
 * guarantees the NEXT save is refused too, and the one after that. One taken
 * slug used to wedge every later write on the page.
 *
 * Total — `keys` is whatever the caller had in its dirty set.
 */
export function retryFieldsAfterRefusal(keys, saveError) {
  const refused = refusedSaveField(saveError);
  const list = Array.isArray(keys) ? keys : [];
  return list.filter((k) => k !== refused);
}

/** The meta fields the top bar and the inspector render. */
export const META_FIELDS = Object.freeze(['title', 'slug', 'status']);

/** The meta bag a page row describes. Same coercions load() and restore use. */
export function metaFromPage(page) {
  const p = page && typeof page === 'object' ? page : {};
  return { title: p.title || '', slug: p.slug || '/', status: p.status || 'draft' };
}

/**
 * Meta re-synced from a successful PATCH response.
 *
 * THE PHANTOM-SLUG FIX. retryFieldsAfterRefusal drops a refused field from the
 * dirty set so one taken slug cannot poison every later save — but the refused
 * VALUE stayed in `meta`, which is what the slug box renders. The box then
 * showed a value that existed nowhere but this browser, and the next
 * successful save of anything else cleared the error banner, leaving the chip
 * reading "Saved" over a slug the server had never accepted.
 *
 * `dirtyFields` is the set still queued when the response lands. Those belong
 * to the OPERATOR — they were typed after this PATCH went out — and are
 * skipped, which is what stops the re-sync from eating keystrokes.
 *
 * Returns `current` unchanged when nothing moved, so React can bail out.
 */
export function resyncMeta(current, page, dirtyFields) {
  const cur = current && typeof current === 'object' ? current : {};
  // No page in the response is not authority to overwrite anything.
  if (!page || typeof page !== 'object') return cur;
  const server = metaFromPage(page);
  const dirty = dirtyFields instanceof Set
    ? dirtyFields
    : new Set(Array.isArray(dirtyFields) ? dirtyFields : []);
  let changed = false;
  const next = { ...cur };
  for (const k of META_FIELDS) {
    if (dirty.has(k)) continue;
    if (next[k] !== server[k]) { next[k] = server[k]; changed = true; }
  }
  return changed ? next : cur;
}

/**
 * Sticky per-field refusals: { slug: { message, value } }.
 *
 * The top-bar banner rides on `saveError`, which the next successful save
 * clears. A refusal whose field is no longer queued would therefore vanish
 * from the screen while its cause was still unresolved — so it is recorded
 * against the FIELD, with the value that was rejected, and cleared only when a
 * write actually carries that field (or a restore replaces the page).
 */
export function recordRefusal(refusals, saveError, payload) {
  const base = refusals && typeof refusals === 'object' ? refusals : {};
  const field = refusedSaveField(saveError);
  if (!field) return base;
  const p = payload && typeof payload === 'object' ? payload : {};
  return { ...base, [field]: { message: String(saveError), value: p[field] } };
}

/** Drops refusals for fields a write has now carried. Identity when no match. */
export function clearRefusals(refusals, fields) {
  const base = refusals && typeof refusals === 'object' ? refusals : {};
  const list = Array.isArray(fields) ? fields : [];
  if (!list.some((k) => Object.prototype.hasOwnProperty.call(base, k))) return base;
  const next = { ...base };
  for (const k of list) delete next[k];
  return next;
}

// ---------------------------------------------------------------------------
// Structured list fields — FAQ / Ranking / Comparison / Product grid
//
// These four blocks are LIST-SHAPED: their content prop is an array of row
// objects the server renderer walks. Every helper below is TOTAL, for the
// usual reason — the array is operator/AI-authored JSON and can legally hold
// a null, a string, or a nested array.
//
// FILTERING IS DELIBERATE AND MIRRORS THE RENDERER. funnelRender.js does
// `.filter(isPlainObject)` on ranking.items, faq.items, comparison_table.rows
// and product_grid.items — a non-object row is ALREADY invisible on the public
// page. Showing it in the editor would be the panel promising to edit
// something the page will never print, so `listRows` drops it on read and the
// first edit normalizes it away.
// ---------------------------------------------------------------------------

/** A plain object — not null, not an array. Same test the renderer applies. */
function isRowObject(v) {
  return !!v && typeof v === 'object' && !Array.isArray(v);
}

/**
 * The rows a list-shaped prop actually renders as: plain objects only.
 * Anything else (null, string, nested array) is dropped, exactly as
 * funnelRender.js drops it.
 *
 * RETURNS THE INPUT ARRAY UNCHANGED when there is nothing to drop, and that
 * identity is load-bearing rather than an optimization. Every mutation helper
 * below returns `listRows(rows)` on a no-op path, and RowsField writes only
 * when the result is a DIFFERENT array — so `↑` on the first row, a remove
 * past the end, or a refused column rename must come back as the very same
 * array or the panel would push an identical props value through commit() and
 * bank an undo step that undoes nothing.
 */
export function listRows(value) {
  if (!Array.isArray(value)) return [];
  return value.every(isRowObject) ? value : value.filter(isRowObject);
}

/** Append a row. `defaultRow` is shallow-copied so the registry's literal is never shared. */
export function addListRow(rows, defaultRow) {
  return [...listRows(rows), isRowObject(defaultRow) ? { ...defaultRow } : {}];
}

/**
 * Drop row `index`. An out-of-range index returns the SAME array identity, so
 * the caller can skip the write and no empty history entry is recorded.
 */
export function removeListRow(rows, index) {
  const list = listRows(rows);
  if (!Number.isInteger(index) || index < 0 || index >= list.length) return list;
  return list.filter((_, i) => i !== index);
}

/**
 * Move row `index` by `delta` (-1 up, +1 down). A move that would leave the
 * array returns the SAME array identity — that is what makes the ↑ on the
 * first row a no-op rather than a silent reorder or a crash.
 */
export function moveListRow(rows, index, delta) {
  const list = listRows(rows);
  const to = index + delta;
  if (!Number.isInteger(index) || !Number.isInteger(delta) || delta === 0) return list;
  if (index < 0 || index >= list.length || to < 0 || to >= list.length) return list;
  const next = list.slice();
  const [moved] = next.splice(index, 1);
  next.splice(to, 0, moved);
  return next;
}

/**
 * Write one cell.
 *
 * `undefined` DELETES the key; an empty STRING is kept. The difference is
 * load-bearing for comparison tables: the renderer derives the column set from
 * `Object.keys(rows[0])`, so letting a cleared text cell delete its key would
 * make emptying the first row's cell delete the whole COLUMN from the page.
 */
export function setListCell(rows, index, key, value) {
  const list = listRows(rows);
  if (!Number.isInteger(index) || index < 0 || index >= list.length) return list;
  if (typeof key !== 'string' || !key) return list;
  return list.map((row, i) => {
    if (i !== index) return row;
    const next = { ...row };
    if (value === undefined) delete next[key];
    else next[key] = value;
    return next;
  });
}

// ---------------------------------------------------------------------------
// Comparison table columns
//
// MIRRORS THE RENDERER EXACTLY. funnelRender.js comparison_table reads
//   const cols = Object.keys(rows[0]).filter((k) => k !== 'feature');
// — the FIRST row alone decides the columns, and every later row is read as
// `r[c] ?? ''`. So a key present only on row 3 is invisible on the page, and
// the editor must not draw a cell for it. Every mutation below therefore
// applies to EVERY row, which is what keeps row 0 (the header source) and the
// body in agreement.
// ---------------------------------------------------------------------------

/** The column names the published page will print, in the order it prints them. */
export function comparisonColumns(rows) {
  const list = listRows(rows);
  if (!list.length) return [];
  return Object.keys(list[0]).filter((k) => k !== 'feature');
}

/** A syntactically usable column name, or null. Blank and the reserved key. */
function columnNameValid(name) {
  const n = typeof name === 'string' ? name.trim() : '';
  if (!n || n === 'feature') return null;
  return n;
}

/** Every key present on ANY row, printed or not. */
function allRowKeys(rows) {
  const seen = new Set();
  for (const r of listRows(rows)) for (const k of Object.keys(r)) seen.add(k);
  return seen;
}

/**
 * Keys that exist on some row but are NOT printed by the page, because
 * funnelRender derives its headers from row 0 alone. On a table this editor
 * authored the set is empty; a hand-edited paste or an AI batch can leave real
 * data sitting in cells the published table has no column for, and silently
 * not showing it is how that data gets destroyed by the next edit.
 *
 * @returns {string[]} sorted, so the panel's message is stable
 */
export function hiddenColumnKeys(rows) {
  const printed = new Set(comparisonColumns(rows));
  const out = [];
  for (const k of allRowKeys(rows)) {
    if (k !== 'feature' && !printed.has(k)) out.push(k);
  }
  return out.sort();
}

/** How many rows carry at least one key the published table does not print. */
export function rowsWithHiddenKeys(rows) {
  const printed = new Set(comparisonColumns(rows));
  return listRows(rows).filter((r) =>
    Object.keys(r).some((k) => k !== 'feature' && !printed.has(k))
  ).length;
}

/**
 * Append a column to EVERY row. Identity when the name is unusable — or when
 * there are NO ROWS.
 *
 * The empty case is not a nicety. A column lives inside the row objects, so
 * with zero rows there is nowhere to write it: `[].map()` would hand back a
 * fresh empty array, the panel would see a "change", and every click would
 * bank an undo step for a button that cannot do anything. Worse, the table
 * renders NOTHING at zero rows (funnelRender returns '' before it ever looks
 * at the columns), so the honest move is to make the caller add a row first.
 *
 * PRESERVES AN EXISTING VALUE rather than blanking it. Adding a column whose
 * key already sits on a non-first row is how an operator PROMOTES hidden data
 * into the published table — the whole remedy for a heterogeneous legacy row.
 * An unconditional `[n]: ''` destroyed exactly the data the click was trying
 * to surface. Only a genuinely absent cell is seeded empty, and `??` is
 * deliberate over `||` so a stored '' or 0 survives as itself.
 */
export function addComparisonColumn(rows, name) {
  const list = listRows(rows);
  if (!list.length) return list;
  const n = columnNameValid(name);
  // Already a PRINTED column — that is a real duplicate and is refused.
  if (!n || comparisonColumns(list).includes(n)) return list;
  return list.map((r) => ({ ...r, [n]: r[n] ?? '' }));
}

/**
 * True when reordering would change the PUBLISHED column set.
 *
 * Row 0 is the header source, so moving a row with different keys into (or out
 * of) position 0 silently rewrites the live table's columns — a reorder that
 * looks cosmetic but is not. Rows are homogeneous when this editor authored
 * them; they need not be when an AI batch or a hand-edited paste did.
 */
export function moveWouldChangeColumns(rows, index, delta) {
  const before = listRows(rows);
  const after = moveListRow(before, index, delta);
  if (after === before) return false;
  return JSON.stringify(comparisonColumns(before)) !== JSON.stringify(comparisonColumns(after));
}

/**
 * True when DELETING a row would change the published column set.
 *
 * The move guard shipped without this twin, which left the two doors to the
 * same hazard guarded unequally: reordering row 0 was blocked with prose while
 * one trash click on the same row silently rewrote every header. Reproduced on
 *   [{feature:'a',Us:'1'},{feature:'b',Them:'2'}]
 * — deleting row 0 took the table from Us to Them. Deleting the LAST row is a
 * different act (the table stops rendering at all, which the empty state
 * already says) and is not treated as a column change.
 */
export function removeWouldChangeColumns(rows, index) {
  const before = listRows(rows);
  const after = removeListRow(before, index);
  if (after === before || !after.length) return false;
  return JSON.stringify(comparisonColumns(before)) !== JSON.stringify(comparisonColumns(after));
}

/**
 * How many stored entries this editor cannot represent — nulls, strings,
 * tuple-arrays left by an older format.
 *
 * The renderer ALREADY drops these (`.filter(isPlainObject)`), so the page
 * loses nothing when they go. What was wrong is that the editor dropped them
 * SILENTLY from stored data on the first keystroke: the operator had no way to
 * know a block still held them, or that typing one character would discard
 * them for good. Counting them lets the panel say so before any write.
 */
export function legacyRowCount(value) {
  if (!Array.isArray(value)) return 0;
  return value.length - value.filter(isRowObject).length;
}

/**
 * Rename a column IN PLACE on every row — key order is rebuilt rather than
 * patched, because `{...r, [to]: v}` after a delete would move the column to
 * the END and silently reorder the published table's headers.
 */
export function renameComparisonColumn(rows, from, to) {
  const list = listRows(rows);
  if (typeof from !== 'string' || !comparisonColumns(list).includes(from)) return list;
  const n = columnNameValid(to);
  if (!n || n === from) return list;
  // COLLISION IS TESTED AGAINST EVERY ROW, not just the printed header set.
  // The rename rebuilds each row key by key, so a target that already exists
  // further down collides mid-rebuild and one of the two values is written
  // over the other — silent, unrecoverable cell loss on a row the operator may
  // not even have scrolled to. Reproduced on
  //   [{feature:'a',Us:'1'},{feature:'b',Us:'2',Them:'REAL'}]
  // where renaming Us→Them destroyed row 1's `Us` value. Testing row 0 alone
  // could not see it, because `Them` is not a printed column there.
  if (allRowKeys(list).has(n)) return list;
  return list.map((r) => {
    const next = {};
    for (const k of Object.keys(r)) {
      if (k === from) next[n] = r[k];
      else next[k] = r[k];
    }
    return next;
  });
}

/** Drop a column from every row. Identity when the column is not present. */
export function removeComparisonColumn(rows, name) {
  const list = listRows(rows);
  if (typeof name !== 'string' || !comparisonColumns(list).includes(name)) return list;
  return list.map((r) => {
    const next = { ...r };
    delete next[name];
    return next;
  });
}

/**
 * The row a comparison table's "Add row" must insert: `feature` plus one EMPTY
 * cell per CURRENT column. A row that skipped the columns would render as a
 * line of blanks and — if it ever became row 0 — would delete every column
 * from the page.
 */
export function comparisonDefaultRow(rows, feature) {
  const out = { feature: typeof feature === 'string' ? feature : 'New feature' };
  for (const c of comparisonColumns(rows)) out[c] = '';
  return out;
}

// ---------------------------------------------------------------------------
// Countdown deadline
//
// The renderer emits the deadline as an ATTRIBUTE (`data-deadline`, esc()'d)
// and its runtime reads it with getAttribute + Date.parse. The value is never
// spliced into the emitted JS, so no backtick/${}/backslash constraint applies
// to it — but it MUST be something Date.parse understands, which is why the
// panel stores a full ISO instant rather than the browser's zone-less
// `datetime-local` string.
//
// THE TRIM IS THE SHARED CONTRACT, AND IT LIVES AT EMISSION.
// funnelRender.js renders the attribute as
//   data-deadline='${esc(String(p.deadline || '').trim())}'
// so the runtime never sees the padding: it reads an already-trimmed value and
// runs `if(!raw) return;` then `Date.parse(raw)`. Everything here is measured
// against THAT — the trimmed value — because that is what reaches the page.
//
// This used to be the other way round. Before the renderer trimmed, a padded
// deadline was genuinely dead on the page (V8 answers NaN for
// `Date.parse(' 2026-01-01T00:00:00Z ')`), and this preview had to refuse to
// draw a clock for it. The renderer now trims at emission, which revived every
// legacy padded value — so a preview that still called them dead would state
// the falsehood in the opposite direction. It trims again, in step.
//
// isoFromLocalInput — the WRITE — also trims, so values this editor stores are
// clean at rest as well as at emission. Two independent guarantees, both kept.
//
// ZONE HANDLING IS NOT UNIFORM, and the doc used to claim it was. Per the ES
// spec, a DATE-ONLY string is UTC while a date-TIME string without a zone is
// LOCAL — verified in this runtime (Europe/Madrid):
//   Date.parse('2026-01-01')          → 2026-01-01T00:00:00.000Z  (UTC)
//   Date.parse('2026-01-01T00:00:00') → 2025-12-31T23:00:00.000Z  (local)
// The picker always supplies a date-TIME, so the local reading is the one that
// applies here; the date-only case is reachable only through legacy values.
// ---------------------------------------------------------------------------

/**
 * `datetime-local` value (`2026-12-31T23:59`) → ISO instant.
 *
 * A date-TIME without a zone is read as LOCAL — the zone the operator typed it
 * in. Blank or unparseable returns '' so the caller deletes the prop instead of
 * writing a deadline the runtime would ignore.
 *
 * TRIMS ON PURPOSE: this is the write path, and it is what guarantees every
 * value this editor stores is one `Date.parse` accepts on the public page.
 *
 * The picker carries no seconds, so a stored deadline always lands on :00.
 */
export function isoFromLocalInput(value) {
  const raw = typeof value === 'string' ? value.trim() : '';
  if (!raw) return '';
  const ms = Date.parse(raw);
  if (!Number.isFinite(ms)) return '';
  return new Date(ms).toISOString();
}

/**
 * ISO instant → the `datetime-local` string the input renders, in the
 * operator's LOCAL zone. Unparseable returns '' — an invalid deadline shows as
 * an empty picker, and the raw value is surfaced next to it rather than
 * silently rewritten.
 *
 * The year is zero-padded to four digits: `getFullYear()` returns 41 for a
 * year-41 instant, and `41-01-01T00:00` is not a value the input will accept.
 */
export function localInputFromIso(value) {
  const raw = typeof value === 'string' ? value.trim() : '';
  if (!raw) return '';
  const ms = Date.parse(raw);
  if (!Number.isFinite(ms)) return '';
  const d = new Date(ms);
  const p = (n) => (n < 10 ? '0' : '') + n;
  const year = String(d.getFullYear()).padStart(4, '0');
  return `${year}-${p(d.getMonth() + 1)}-${p(d.getDate())}T${p(d.getHours())}:${p(d.getMinutes())}`;
}

// Strips a SECONDS component (and any fraction) from a datetime-local string,
// leaving `YYYY-MM-DDTHH:MM`. Anchored on the whole shape so it can only ever
// remove a third `:SS` group — a naive `/:\d{2}$/` would eat the MINUTES off
// `2026-06-15T12:00`.
const LOCAL_SECONDS_TAIL_RE = /^(\d{4,}-\d{2}-\d{2}T\d{2}:\d{2}):\d{2}(?:\.\d+)?$/;

/**
 * DST honesty check for a value the operator just picked.
 *
 * WHAT THIS DETECTS: the spring-forward GAP. Once a year a local wall clock
 * time simply does not happen (02:30 on the changeover date), and `Date.parse`
 * resolves it silently to a different time — so the picker would snap an hour
 * without explanation. Round-tripping catches it: what comes back out is not
 * what went in.
 *
 * WHAT THIS DOES NOT DETECT, and the copy must not claim it does: the
 * AMBIGUOUS fall-back hour. When 02:30 happens twice, both occurrences render
 * back as the same local string, so the round trip is clean and nothing fires.
 * Verified in Europe/Madrid — 2026-10-25T02:00, T02:30 and T01:30 all return
 * null, and the stored instant is the FIRST (pre-change) occurrence. That is a
 * real silent choice; it is simply not one this check can see.
 *
 * SECONDS ARE NOT AN ANOMALY. The picker is minute-resolution (step=60), so a
 * value carrying `:30` seconds round-trips to a string one component shorter.
 * Comparing raw would have raised a DST warning on every such value.
 *
 * @returns {null|{stored:string}} null when the pick round-trips to the same
 *          wall-clock MINUTE.
 */
export function localInputAnomaly(value) {
  const raw = typeof value === 'string' ? value.trim() : '';
  if (!raw) return null;
  const iso = isoFromLocalInput(raw);
  if (!iso) return null;
  const back = localInputFromIso(iso);
  const atMinute = raw.replace(LOCAL_SECONDS_TAIL_RE, '$1');
  return back === atMinute ? null : { stored: back };
}

/**
 * What the countdown clock reads, for the canvas preview.
 *
 * MIRRORS THE WHOLE PIPELINE funnelRender.js SHIPS — emission AND runtime:
 * the block's `.trim()` at emission, then countdownRuntimeScript()'s
 * `if(!raw) return`, its `Date.parse`, its
 * `(d>0?d+'d ':'')+pad(h)+':'+pad(m)+':'+pad(s)` clock, and the literal
 * 'Offer expired' once the instant is past. A preview that formatted it
 * differently would be a preview of a page that does not exist — which is
 * exactly what the old hard-coded `23:59:59` was.
 *
 * `state` lets the canvas distinguish the three NON-TICKING cases the runtime
 * treats as one silent no-op: no deadline, an unparseable deadline, and a real
 * expiry. Only the last one is the block working as intended.
 *
 * @returns {{state:'unset'|'invalid'|'expired'|'live', text:string}}
 */
export function countdownPreview(deadline, nowMs) {
  // TRIMMED, because the RENDERER trims at emission — `String(p.deadline ||
  // '').trim()` — so the trimmed value is what the attribute carries and what
  // the runtime parses. Two consequences follow directly from that expression
  // and are asserted against it in the harness:
  //   · a padded but otherwise valid instant reaches the page intact → LIVE
  //   · a whitespace-ONLY value trims to '', so the attribute is empty and the
  //     runtime's `if(!raw) return` fires → indistinguishable from unset, and
  //     reported as unset rather than as a separate broken state
  // `deadline || ''` — the renderer's EXACT expression, not `== null`. They
  // diverge on every falsy non-null value: for a stored `0` the renderer emits
  // an empty attribute (dead page), while `== null` kept the '0' and
  // Date.parse('0') answers a real year-2000 instant — so the canvas drew a
  // ticking clock for a block the page leaves blank. Same class of lie as the
  // whitespace bug, reached through a different operator.
  const raw = String(deadline || '').trim();
  if (!raw) return { state: 'unset', text: '—' };
  const end = Date.parse(raw);
  if (!Number.isFinite(end)) return { state: 'invalid', text: '—' };
  const now = Number.isFinite(nowMs) ? nowMs : Date.now();
  const ms = end - now;
  if (ms <= 0) return { state: 'expired', text: 'Offer expired' };
  const total = Math.floor(ms / 1000);
  const d = Math.floor(total / 86400);
  const h = Math.floor((total % 86400) / 3600);
  const m = Math.floor((total % 3600) / 60);
  const s = total % 60;
  const pad = (n) => (n < 10 ? '0' : '') + n;
  return { state: 'live', text: `${d > 0 ? `${d}d ` : ''}${pad(h)}:${pad(m)}:${pad(s)}` };
}

// ---------------------------------------------------------------------------
// Unrecognised props
// ---------------------------------------------------------------------------

/**
 * Props stored on a block that NO editor field owns.
 *
 * Blocks authored by an older tool carry different key names for the same
 * content — FAQ `question`/`answer`, ranking `title`/`desc`, product grid
 * `image_url`/`link`, sticky CTA `label`/`url`, testimonial `text`/`name`,
 * embed `code`/`src`. The renderer does not read any of them, so the block
 * renders empty AND every editor box opens blank: the operator sees a block
 * with content in the database, no content on the page, and no explanation.
 *
 * Listing them read-only is the honest minimum. It does not migrate anything —
 * guessing that `question` means `q` is a data rewrite this panel has no
 * mandate for — but it turns a silent void into a visible fact the operator
 * can act on.
 *
 * `knownKeys` is INJECTED (the registry is JSX and this file stays
 * dependency-free), and the shared inspector keys are excluded here so every
 * caller does not have to remember them.
 *
 * @returns {string[]} sorted, so the panel's line is stable across renders
 */
export const SYSTEM_PROP_KEYS = Object.freeze(['block_name', 'style', 'mobile_styles']);

export function unrecognisedProps(props, knownKeys) {
  const p = props && typeof props === 'object' && !Array.isArray(props) ? props : {};
  const known = new Set([
    ...(Array.isArray(knownKeys) ? knownKeys : []),
    ...SYSTEM_PROP_KEYS,
  ]);
  return Object.keys(p).filter((k) => !known.has(k)).sort();
}

// ---------------------------------------------------------------------------
// AI op wiring floor
// ---------------------------------------------------------------------------

/**
 * Props whose value is WIRING, not copy: drop one and the block still renders
 * but no longer charges, no longer resolves a variant, or silently loses the
 * operator's layout. `replace_props` is a wholesale overwrite, so an AI batch
 * that re-emits a block's copy without re-emitting these would delete them.
 *
 * MIRRORED SERVER-SIDE in routes/aiDeveloper.js (WIRING_KEYS) — the client
 * floor keeps the on-screen draft honest, the server floor keeps the ops the
 * model is told it applied honest. Both lists must move together.
 *
 * Membership rule: a key belongs here when losing it changes what the block
 * DOES rather than what it SAYS. `style`/`mobile_styles` qualify because the
 * inspector is the only place they are authored — an AI batch that has never
 * seen them cannot re-emit them.
 *
 * THE SECOND WAVE (seam audit B3). The original nine covered the checkout
 * blocks that existed when the floor was written; every block type added since
 * had load-bearing props outside it. A routine "reword this" batch blanked
 * sticky_cta.href (money link → '#'), product_grid.items (grid gone),
 * countdown.deadline (clock dead), embed.html (widget erased), table.rows
 * (table emptied), order_bump.checked (pre-ticked bump unticks) and
 * hero.cta_href — all while the canvas still looked right.
 *
 * items/rows/html are CONTENT the model legitimately rewrites, and they belong
 * here anyway: the contract is not "read-only", it is "silence does not
 * delete". An op that actually emits them still wins, including an explicit
 * null. Both directions are asserted per key in the ai-ops-wiring harness.
 */
export const WIRING_KEYS = Object.freeze([
  'variant_id',
  'line_items',
  'offer_id',
  'quantity',
  'product_id',
  'price_id',
  'style',
  'mobile_styles',
  'block_name',
  // seam audit B3 — the second wave
  'href',
  'cta_href',
  'url',
  'deadline',
  'html',
  'items',
  'rows',
  'checked',
]);

/**
 * The props a `replace_props` op should actually produce.
 *
 * `next` wins for every key it SETS — including setting one to null/'' , which
 * is an explicit clear and is honored. A wiring key the op is simply SILENT
 * about is carried forward from `prev`. That is the whole floor: an AI batch
 * can change wiring on purpose, it just cannot drop it by omission.
 *
 * Total by construction — `prev`/`next` are whatever was in the JSON.
 */
export function mergeReplaceProps(prev, next) {
  const p = prev && typeof prev === 'object' && !Array.isArray(prev) ? prev : {};
  const n = next && typeof next === 'object' && !Array.isArray(next) ? next : {};
  const out = { ...n };
  for (const k of WIRING_KEYS) {
    if (Object.prototype.hasOwnProperty.call(n, k)) continue; // explicitly set
    if (Object.prototype.hasOwnProperty.call(p, k)) out[k] = p[k];
  }
  return out;
}
