-- Cache the AI Brand Intel result on the brand row so the Overview tab can
-- render instantly instead of waiting 7-8 s for a Claude Haiku round-trip on
-- every page load. Invalidates naturally: when last_scraped_at advances past
-- intel_scraped_at the cached payload is treated as stale and regenerated.

ALTER TABLE brand_spy.brands
  ADD COLUMN IF NOT EXISTS intel_payload     JSONB,
  ADD COLUMN IF NOT EXISTS intel_scraped_at  TIMESTAMPTZ;

COMMENT ON COLUMN brand_spy.brands.intel_payload IS
  'Cached AI Brand Intel JSON ({personas, adAngles, usps, desires, emotions, themes}). Generated by Claude Haiku in /brands/:id/intel.';
COMMENT ON COLUMN brand_spy.brands.intel_scraped_at IS
  'The value of brand_spy.brands.last_scraped_at at the time intel_payload was generated. When this < last_scraped_at, the cache is stale.';
